<?php
/**
 * Template file for hire purchase installment plan rendering.
 *
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2019-present heidelpay GmbH. All rights reserved.
 * @link  http://dev.heidelpay.com/magento2
 * @author  Simon Gabriel
 *
 * @package  Heidelpay\magento2
 *
 * @var $block Hgw
 */

use Heidelpay\Gateway\Block\Hgw;
?>

<div style="width:100%; display:flex; flex-wrap: wrap;justify-content: center;">
    <div>
        <img src="https://www.santander.de/media/bilder/logos/logos_privatkunden/logo.gif"/>
        <div class="hgw_installment_plan">
            <strong><?php echo __('Hire Purchase Precontract') ?><br/></strong>
            <a href="<?php echo trim($block->getInstallmentPlanUrl()) ?>" target="_blank"><?php echo __('Hire Purchase Precontract download') ?></a>
        </div>
        <br /><br />

        <form id="hp-confirm-form" method="post" action="<?php echo $block->getUrl('Heidelpay_Gateway/hgw'); ?> ">
            <input type="hidden" name="referenceId" value="<?php echo $block->getInitReferenceId(); ?>">
            <button id="pay-now" type="submit" style="margin-left:200px">
                <span><?php echo __('pay now') ?></span>
            </button>
        </form>
    </div>
</div>
