<?php
/**
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2016-present heidelpay GmbH. All rights reserved.
 * @link https://dev.heidelpay.de/magento
 * @author Stephano Vogel
 */
/**
 * @var $block \Heidelpay\Gateway\Block\Info\InvoiceSecured
 */
?>
<dl class="payment-method invoice-secured">
    <dt class="title"><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php if ($block->getTransactionInfo() !== null && ! empty($block->printAdditionalInformationHtml())) : ?>
        <dd class="content">
            <strong><?php echo $block->escapeHtml(__('Payment information')) ?></strong><br />
            <?php echo $block->printAdditionalInformationHtml() ?>
        </dd>
    <?php endif; ?>
</dl>