<?php
/**
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2016-present heidelpay GmbH. All rights reserved.
 * @link http://dev.heidelpay.com/magento2
 * @author Stephano Vogel
 */
/**
 * @var $block \Heidelpay\Gateway\Block\Info\InvoiceSecured
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?>
    {{pdf_row_separator}}
<?php echo __('Account Holder') . ': ' . $block->escapeHtml($block->getAccountHolder()); ?>
    {{pdf_row_separator}}
<?php echo __('IBAN') . ': ' . $block->escapeHtml($block->getAccountIban()); ?>
    {{pdf_row_separator}}
<?php echo __('BIC') . ': ' . $block->escapeHtml($block->getAccountBic()); ?>
    {{pdf_row_separator}}
<?php echo __('Identification Number') . ': ' . $block->escapeHtml($block->getIdentificationNumber()); ?>
    {{pdf_row_separator}}